### PR TITLE
Fix allocations test errors

### LINKED ISSUE #145: Fix allocation tests
Some operators incur allocations in the unit tests:

https://github.com/JuliaSmoothOptimizers/ShiftedProximalOperators.jl/actions/runs/18427091179/job/52524497744?pr=144#step:6:297

### PR DESCRIPTION
**Pull request by MaxenceGollier**
closes #145 

See [#145 (comment)](https://github.com/JuliaSmoothOptimizers/ShiftedProximalOperators.jl/issues/145#issuecomment-3608602201).

I guess that test will fail on lts with this but we should try to make 0 allocations on lts and not the other way around.

### CODE REVIEW

**Comment by MaxenceGollier** [comment]
💪 [QRMumps.jl#136](https://github.com/JuliaSmoothOptimizers/QRMumps.jl/pull/136) should fix for Julia 1 now.

Just need to solve on nightly.

**Comment by amontoison** [comment]
@MaxenceGollier I suggest to use `pre` (for pre-release) instead of `nightly` for the unit tests.

**Comment by MaxenceGollier** [comment]
For your info @amontoison, I was able to solve the issue on Julia `pre` by updating the wrappedallocs macro, I don't know if you use it in other packages, you might find it useful if you run into similar errors.
I just call the function twice and use the allocated macro on the second call.

I only have the QRMumps.jl related failures now.

File: test/test_allocs.jl [hunk 1]
```diff
@@ -29,6 +29,7 @@ macro wrappedallocs(expr)
   argnames = [gensym() for a in expr.args]
   quote
     function g($(argnames...))
+      $(Expr(expr.head, argnames...))
```
Comment (amontoison) [inline test/test_allocs.jl:32]: Oh, do you do the warm-start this way?
It is neat!
